# Generated by Django 5.0.1 on 2024-02-06 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grades', models.CharField(blank=True, choices=[('Grade 1', 'Grade1'), ('Grade 2', 'Grade2'), ('Grade 3', 'Grade3'), ('Grade 4', 'Grade4'), ('Grade 5', 'Grade5'), ('Grade 6', 'Grade6'), ('Grade 7', 'Grade7'), ('Grade 8', 'Grade8'), ('Grade 9', 'Grade9'), ('Grade 10', 'Grade10'), ('Grade 11', 'Grade11'), ('Grade 12', 'Grade12')], max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField(max_length=500)),
                ('catagory', models.CharField(choices=[('CATAGORY A', 'CATAGORYA'), ('CATAGORY B', 'CATAGORYB'), ('CATAGORY C', 'CATAGORYC'), ('CATAGORY D', 'CATAGORYD')], max_length=30)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('am', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_manager', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(to='school_app.grades')),
                ('om', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
