version: '3.9'
services:
  crm_backend:
    build: ./Back-End
    container_name: crm_backend
    # ports:
    #   - 8000:8000
    volumes:
      - ./Back-End:/app
    env_file:
      - ./Back-End/.env
    depends_on:
      - crmdb
      - redis_cache
  
  nginx:
    image: nginx:latest
    container_name: nginx
    # restart: always
    ports:
      - 80:80
    volumes:
      - ./Back-End/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Back-End:/app
    depends_on:
      - redis_cache
      - crmdb
      - crm_backend
      - celery_flower
      - celery_worker

  crmdb:
    image: postgres
    container_name: crmdb
    ports:
      - 5432:5432
    restart: always
    volumes:
      - crm_pg_data:/var/lib/postgresql/data
    env_file:
      - ./Back-End/.env
  
  redis_cache:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379
  
  celery_worker:
    build: ./Back-End
    container_name: celery_worker
    # command: celery -A training worker -l INFO --concurrency=4 -E
    command: celery -A training worker --concurrency=4 -l INFO --without-gossip --without-mingle --without-heartbeat -Ofair --pool=solo -E 
    volumes:
      - ./Back-End:/app
    env_file:
      - ./Back-End/.env
    depends_on:
      - crm_backend
      - redis_cache
  
  celery_flower:
    image: mher/flower
    container_name: celery_flower
    restart: always
    command: celery flower --persistent=True --port=5555 --basic_auth=shoib@gmail.com:1234
    env_file:
      - ./Back-End/.env
    ports:
      - 5555:5555
    depends_on:
      - celery_worker
      - redis_cache

volumes:
  crm_pg_data: