version: '3.9'
services:
  crm_backend:
    build: ./Back-End
    container_name: crm_backend
    ports:
      - 8000:8000
    volumes:
      - ./Back-End:/app
    env_file:
      - ./Back-End/.env
    depends_on:
      - crmdb
      - redis_cache
  
  nginx:
    image: nginx:latest
    container_name: nginx
    # restart: always
    ports:
      - 80:80
    volumes:
      - ./Back-End/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./Back-End:/app
    depends_on:
      - crm_backend

  crmdb:
    image: postgres
    container_name: crmdb
    ports:
      - 5432:5432
    restart: always
    volumes:
      - crm_pg_data:/var/lib/postgresql/data
    env_file:
      - ./Back-End/.env
  
  redis_cache:
    image: redis
    container_name: redis_cache
    restart: always
    ports:
      - 6379:6379
  
  celery_worker:
    build: ./Back-End
    container_name: celery_worker
    command: celery -A training worker -l INFO --concurrency=4 -E
    volumes:
      - ./Back-End:/app
    env_file:
      - ./Back-End/.env
    depends_on:
      - crm_backend

volumes:
  crm_pg_data: