# Generated by Django 5.0.1 on 2024-02-20 12:42

import account_app.userEnums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TRAINER', 'TRAINER'), ('AM', 'AM'), ('OM', 'OM')], default=account_app.userEnums.UserType['TRAINER'], max_length=30),
        ),
    ]
