# Generated by Django 5.0.1 on 2024-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_role_remove_user_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TRAINER', 'TRAINER'), ('AM', 'AM'), ('OM', 'OM')], default='TRAINER', max_length=30, unique=True),
        ),
    ]
