# Generated by Django 4.2.4 on 2023-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='erp_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
