# Generated by Django 4.2.4 on 2023-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_school_contact_alter_school_erp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='trainingStatus',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], default='Pending', max_length=50),
        ),
    ]
