# Generated by Django 4.2.4 on 2023-11-07 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Grade9', 'Grade9'), ('Grade10', 'Grade10'), ('Grade11', 'Grade11'), ('Grade12', 'Grade12')], max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=500)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('erp_code', models.CharField(blank=True, max_length=12, null=True)),
                ('am', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='academic_manager', to=settings.AUTH_USER_MODEL)),
                ('grades', models.ManyToManyField(to='Schools.grades')),
                ('om', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='operation_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
