# Generated by Django 4.2.4 on 2023-11-14 17:25

import Schools.models.TrainingStatus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='training_status',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], default=Schools.models.TrainingStatus.TrainingStatus['PENDING'], max_length=20, null=True),
        ),
    ]
