# Generated by Django 4.2.4 on 2023-11-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_alter_school_erp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
