# Generated by Django 4.2.4 on 2023-11-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_school_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grades',
            old_name='grade',
            new_name='grades',
        ),
    ]
