# Generated by Django 4.2.4 on 2023-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0007_alter_grades_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='grades',
            field=models.CharField(blank=True, choices=[('Grade1', 'Grade1'), ('Grade2', 'Grade2'), ('Grade3', 'Grade3'), ('Grade4', 'Grade4'), ('Grade5', 'Grade5'), ('Grade6', 'Grade6'), ('Grade7', 'Grade7'), ('Grade8', 'Grade8'), ('Grade9', 'Grade9'), ('Grade10', 'Grade10'), ('Grade11', 'Grade11'), ('Grade12', 'Grade12')], default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
