# Generated by Django 5.0.1 on 2024-02-06 09:13

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('startDate', models.DateField(blank=True)),
                ('startTime', models.TimeField(blank=True)),
                ('endTime', models.TimeField(blank=True)),
                ('trainingStatus', models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], default='ONGOING', max_length=50)),
                ('trainingType', models.CharField(blank=True, choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER SCIENCE', 'COMPUTER_SCIENCE'), ('AEROMOELLING', 'AEROMOELLING')], max_length=50)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('grades', models.ManyToManyField(blank=True, to='school_app.grades')),
                ('schools', models.ManyToManyField(blank=True, to='school_app.school')),
                ('trainers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-startDate', 'startTime'],
            },
        ),
    ]
