# Generated by Django 5.0.1 on 2024-02-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='currentGrade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
