# Generated by Django 5.0.1 on 2024-02-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('training_app', '0002_training_currentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='currentGrade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_grade', to='school_app.grades'),
        ),
    ]
