# Generated by Django 5.0.1 on 2024-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0003_alter_training_currentgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='trainingType',
            field=models.CharField(blank=True, choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER SCIENCE', 'COMPUTER_SCIENCE'), ('AEROMODELLING', 'AEROMOELLING'), ('DOUBT SESSION', 'DOUBT_SESSION')], max_length=50),
        ),
    ]
