# Generated by Django 5.0.1 on 2024-02-24 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('training_app', '0004_alter_training_trainingtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDataModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingSheetModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sheet', to='school_app.school')),
                ('trainingData', models.ManyToManyField(blank=True, to='training_app.trainingdatamodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
