# Generated by Django 5.0.1 on 2024-03-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_app', '0005_trainingdatamodel_trainingsheetmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdatamodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='trainingdatamodel',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
