# Generated by Django 4.2.4 on 2023-11-07 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trainingType', models.CharField(choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER_SCIENCE', 'COMPUTER_SCIENCE')], max_length=20)),
                ('trainingStatus', models.CharField(choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], max_length=20)),
                ('startTime', models.TimeField(choices=[('08:00:00', '08:00:00'), ('10:00:00', '10:00:00'), ('12:00:00', '12:00:00'), ('14:00:00', '14:00:00'), ('16:00:00', '16:00:00')])),
                ('endTime', models.TimeField(choices=[('09:30:00', '09:30:00'), ('11:30:00', '11:30:00'), ('01:30:00', '01:30:00'), ('04:00:00', '04:00:00'), ('06:30:00', '06:30:00')])),
                ('date', models.DateField()),
                ('remarks', models.TextField(max_length=500)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Schools.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('trainingStatus', models.CharField(choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], max_length=50)),
                ('trainingType', models.CharField(choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER_SCIENCE', 'COMPUTER_SCIENCE')], max_length=50)),
                ('grades', models.ManyToManyField(to='Schools.grades')),
                ('schools', models.ManyToManyField(to='Schools.school')),
                ('trainers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
