# Generated by Django 4.2.4 on 2023-11-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
        ('Trainings', '0003_alter_training_endtime_alter_training_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='grades',
            field=models.ManyToManyField(blank=True, null=True, to='Schools.grades'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainingType',
            field=models.CharField(choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER SCIENCE', 'COMPUTER_SCIENCE')], max_length=50),
        ),
    ]
