# Generated by Django 4.2.4 on 2023-11-14 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Trainings', '0004_alter_training_grades_alter_training_trainingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='endTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='grades',
            field=models.ManyToManyField(blank=True, to='Schools.grades'),
        ),
        migrations.AlterField(
            model_name='training',
            name='schools',
            field=models.ManyToManyField(blank=True, to='Schools.school'),
        ),
        migrations.AlterField(
            model_name='training',
            name='startDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='startTime',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainingStatus',
            field=models.CharField(blank=True, choices=[('ONGOING', 'ONGOING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainingType',
            field=models.CharField(blank=True, choices=[('ROBOTICS', 'ROBOTICS'), ('COMPUTER SCIENCE', 'COMPUTER_SCIENCE')], max_length=50),
        ),
    ]
