# Generated by Django 4.2.4 on 2023-11-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trainings', '0005_alter_training_endtime_alter_training_grades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='endTime',
            field=models.TimeField(),
        ),
    ]
